server:
  port: 9003

spring:
  application:
    name: EMPLOYEE-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://loclahost:8761/eureka/
  instance:
    hostname: localhost
